apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: janus-test-github-events-test-1769889014575
  annotations:
    github.com/project-slug: 04kash-test-org/janus-test-github-events-test-1769889014575
  description: E2E test component for github events module
spec:
  type: other
  lifecycle: unknown
  owner: user:default/04kash